### ISSUE TITLE
FormRequest ValidationHttpException breaks internal dispatcher requests

### ISSUE THREAD

**Issue by kaiserlos** [dingo/api#1014]
After upgrade to L5.2 internal api request break if my formrequest throws out any ValidationHttpException, external requests are working fine and are responding with the validation errors.

`Type error: Argument 1 passed to Dingo\Api\Exception\InternalHttpException::__construct() must be an instance of Illuminate\Http\Response, instance of Symfony\Component\HttpFoundation\Response given, called in .../vendor/dingo/api/src/Dispatcher.php on line 543`

**Comment by datune** [comment]
I am pretty sure that this is not related to your upgrade, you'll most likely notice the same behaviour on your previous versions as well, but probably never had validation errors happening, which is why you did not notice until now. 

I have reported this bug #845 months ago, to this day I can not get it to work as expected.

**Comment by kaiserlos** [comment]
I downgraded to L5.1 and it works again ...

**Comment by kaiserlos** [comment]
Also watch #1024

**Comment by kaiserlos** [comment]
+1

**Comment by hskrasek** [comment]
Same comment as the one I left on #1024, gonna add this to the list of issues I need to address, once I finished getting caught up and going through the backlog of issues.
