### ISSUE TITLE
InvalidCredentialsException 500 error

### ISSUE THREAD

**Issue by DeanWhitehouse** [dingo/api#1091]
When an `InvalidCredentialsException` error is thrown from `vendor/league/oauth2-server/src/Grant/PasswordGrant.php` Dingo picks up the exception and changes the header response code to 500 if it's not an `HttpExceptionInterface` error

I've found the issue in `/vendor/dingo/api/src/Exception/Handler.php` `line 181`, I've put this in as a quick fix currently but I'm sure there's a better way.

` return $exception instanceof HttpExceptionInterface ? $exception->getStatusCode() : (isset($exception->httpStatusCode) ? $exception->httpStatusCode : 500);`

**Comment by lucasmichot** [comment]
Indeed @DeanWhitehouse but the issue is on `league/oauth2-server` server side:

The `\League\OAuth2\Server\Exception\OAuthException` returns a HTTP code 400 but does not implement
Unless  `\League\OAuth2\Server\Exception\OAuthException` si OK to implements \Symfony\Component\HttpKernel\Exception\HttpExceptionInterface there is no way to "guess" this is actually a HTTP exception

Why not handling this yourself in `\App\Exceptions\Handler::render` ?

```php
    public function render($request, Exception $e)
    {
        if($e instanceof \League\OAuth2\Server\Exception\OAuthException) {
            $e = new BadRequestHttpException($e->getMessage(), $e);
        }

        return parent::render($request, $e);
    }
```

**Comment by DeanWhitehouse** [comment]
@lucasmichot Have tried handling it myself as you suggested but that doesn't work, it seems the exception gets modified before it gets there!

**Comment by hskrasek** [comment]
Will look into and see if there is anything we can do on the dingo side of things.

**Comment by hskrasek** [comment]
@DeanWhitehouse Alright so not really a bug on our end, and also not much we can do. My suggestion would be to register an exception handler for all OAuthExceptions

```php
app('Dingo\Api\Exception\Handler')->register(function (\League\OAuth2\Server\Exception\OAuthException $exception) {
    // create appropriate error response here.
});
```
