### ISSUE TITLE
How can we return 404 for routes that are not defined? 

### ISSUE THREAD

**Issue by iamrutvik** [dingo/api#1093]
I am trying to write this piece of code in Handler.php's render method

`if($this->isHttpException($e))
        {
            switch ($e->getStatusCode())
            {
                // not found
                case 404:
                        throw new \Symfony\Component\HttpKernel\Exception\HttpException\NotFoundHttpException("path not found");
                    });
                    break;

                default:
                    return $this->renderHttpException($e);
                    break;
            }
        }

        return parent::render($request, $e);`

It is showing error(PFA screenshot)
![screenshot 14](https://cloud.githubusercontent.com/assets/19551848/16489768/9667cf6c-3ef4-11e6-9b82-fbabc325e08c.png)

**Comment by tembra** [comment]
Return a 404 Not Found response is the default behavior of Dingo API.
So, what do you mean?

**Comment by iamrutvik** [comment]
I mean it should not return a fancy HTML page. I want to return a JSON response like
`{
     message : 'path not found',
     status_code : 404
}`

Ofcourse HTTP status code must be set to 404

**Comment by tembra** [comment]
It is not clearly yet.

As stated on Dingo API documentation (https://github.com/dingo/api/wiki/Configuration#response-formats) the default response format is JSON.

The error in your image is about a `FatalErrorException` because you wrote some code in Handler.php.
Why are you writing this code? Is it because you want the message to be `path not found` instead of `404 Not Found`?

If you remove your code you will get a JSON response like you defined in your `errorFormat` where `status_code` will be `404` and `message` will be `404 Not Found`.
