### ISSUE TITLE
securing API with facebook Oauth

### ISSUE THREAD

**Issue by Danny-P** [dingo/api#1142]
Hi,

I build my API with dingo and now I'd like to secure it. I don't want to set up a completet OAuth2 Server. Instead I'd like to use the facebook Log-In. 
I integrated OAuth2 Authentication like the documentation said. I get an access token from Facebook and pass it as header to my API. 
But I get the Message "The resource owner or authorization server denied the request." back.
What will I need to setup, too? How to handle Users in this scenario? I didn't find anything at the wiki for that. 
Thank you!

**Comment by crynobone** [comment]
> What will I need to setup, too? How to handle Users in this scenario? I didn't find anything at the wiki for that. 

There no documentation mainly because no body does that. 

You see, when you setup an OAuth2 Server (on your application), you're allowing external application to authenticate to the user on your application. In relative to Facebook, you authenticating the user to access Facebook and not your application. So obviously your application can't understand the token because it not generated by the application, only Facebook understand (and able to fetch data using those token).

**Comment by Danny-P** [comment]
Hi,
Perhaps I didn't understand OAuth2 together with APIs correct.
Will I have to build a webapp, which handles the user registration / profile creation process? In ths registration I can use a Facebook Auth to get profile Information out of the User's Facebook profile to copy it into the profile in my webapp. Than the user authenticates against my webapp to get the access token from my webapp? 
Then I will need to build the same Auth Token Request URIs like facebook did in their app? 
Perphaps that is the missing point in my knowledge about OAuth2.

Thank you!
