### ISSUE TITLE
Laravel 5.3 support 

### ISSUE THREAD

**Issue by filipveschool** [dingo/api#1148]
Hi, could you make it compatible with Laravel 5.3 please?

**Comment by Kaukov** [comment]
#1152 ^^

**Comment by hskrasek** [comment]
@filipveschool This is something I plan on looking into, haven't ruled if I'm going to do so for version 1.0.0 yet, but will add it to the milestone for tracking.

**Comment by ddctd143** [comment]
@hskrasek Could you merge @Kaukov pull request #1152 into 1.0.0 beta branch ?
Looks like tests are passing

**Comment by ddctd143** [comment]
Looks like it won't be so easy.
In 5.2 version ControllerInspector class (Illuminate\Routing\ControllerInspector) was deprecated and in version 5.3 removed completely. Dingo/Api package relies on that class, so current dev or master branch won't work with laravel 5.3

https://laravel.com/api/5.2/Illuminate/Routing/ControllerInspector.html

**Comment by Jaspaul** [comment]
@ddctd143 I've updated a beta project I'm working on using the details from #1152 and adding some additional fixes, and everything appears to be working. Is there something specific that would go wrong regarding the ControllerInspector that I should be aware of?

Code is available at: https://github.com/jaspaul/api

**Comment by hskrasek** [comment]
@ddctd143 #1152 has been merged, but yes you are right. In Laravel 5.3 the ControllerInspector class was removed, because Laravel 5.3 removes the ability to implicitly define routes based on controller methods. Debating on either A) re-implementing the capabilities of the now removed class, to keep the functionality working, or B) remove it from the package all together and "force"/drive people towards explicit route declaration

**Comment by bradbernard** [comment]
My vote is solution B since it's probably less work and follows L5.3 style.

**Comment by ddctd143** [comment]
@hskrasek Checked one project, there was $api->controller, which does not work with L5.3, and that code was a mess, because of controller class had a lot of methods, and it was very hard to find right routing methods. I think thats why laravel removed that functionality. Routing should be declared more verbosely, which leads to better code readability. My vote would be for **B**

**Comment by bradbernard** [comment]
@hskrasek What is the timeline for v1.0.0 release now that L5.3 is supported?

**Comment by hskrasek** [comment]
@ddctd143 and @bradbernard The commit I linked here when closing removes the functionality. So B was the winner. 

@bradbernard I set the milestone for the 4th of September when I started going over everything. Not 100% sure I can make that deadline, so I wouldn't hold me to that. Hoping to soon though

**Comment by bradbernard** [comment]
@hskrasek No rush... I am in awe of how much work you put into this, thank you! Can't wait for the release 👌

**Comment by rustanacexd** [comment]
already works?

**Comment by Ra1da35ma** [comment]
any hopes on this
