### ISSUE TITLE
Using transformers with created/accepted

### ISSUE THREAD

**Issue by denizdogan** [dingo/api#1218]
It would be really useful to be able to use transformers with the `created` and `accepted` response helper methods. Currently it seems impossible, at least I can't figure it out?

**Comment by johannesschobel** [comment]
You can do something like this:

```php
// create a new object and save it to the database
$object = new Object();
$object->name = "test";
$object->save();

// output the result
// e.g, use a transformer with the respective object information and status code
return $this->response
    ->item($object, new ObjectTransformer())
    ->setMeta(/* additional Meta information */)
    ->setStatusCode(201);
```

Does this solve your problem!?

**Comment by denizdogan** [comment]
@johannesschobel Yes, thank you very much!

Would it be possible to include this functionality in Dingo?

**Comment by johannesschobel** [comment]
What do you mean "include this functionality"? This is already fully included in ```dingo/api``` ...

**Comment by denizdogan** [comment]
@johannesschobel Sorry, let me clarify what I meant!

Can we change the definition of `Dingo\Api\Http\Response\Factory::created` and `::accepted` so that we can pass transformer objects for the `$content` parameter? As such:

    $this->response->created('/foo/1', $foo, new FooTransformer)

Currently they only take `$location` and and `$content` as parameters.

**Comment by johannesschobel** [comment]
Aaaaaaah.. not i understand your problem...

Note that ```created()``` only provides one parameter, which is the location of the entity, which was created.. This location can be found in the ```http headers``` of the response (field ```Location``` I think).

In my opinion, both methods (```accepted``` and ```created```) are mainly used to _redirect_ the requestor to another endpoint of your API, where the entity can be requested.
This enhances maintainability of your API, because you can "reuse" already implemented routes (e.g., to show the created entity you may send the requestor the URI to the ```/show/{id}``` route).

I know, that is one more request, for the client, and so on... BUT it makes your API, as well as the communication with the API, more understandable and self-explanatory...

However, if you want to send back "real" data, use the ```collection```, ```item``` or ```paginate``` method (whatever suits your needs best).

**Comment by denizdogan** [comment]
Okay, thank you for the help!

**Comment by hskrasek** [comment]
@denizdogan What @johannesschobel is correct, but the second param on both responses is `$content`. If you give that a Eloquent model or collection of models, Dingos response class will automatically use the transformer you have registered for that model.
