### ISSUE TITLE
Dingo API is not working with dynamic relationships of model

### ISSUE THREAD

**Issue by gauravjain028** [dingo/api#1271]
I have a relationship like 

```
 public function relationXYZ() {
        if(class_exists('Prefix'.ucfirst($this->type), true)) {
            return $this->hasMany('Prefix'.ucfirst($this->type), 'refId');
        }
    }
```
Here I have multiple type, A, B, C, D for example.

and in Transformer when I use code like

```
public function includeRelationXYZ($model) {
        $data = $model->relationXYZ;        

        if(!empty($data)) {
            $className = 'TransformersPrefix'.ucfirst($panel->type);
            return $this->collection($data, new $className, 'relationXYZ');
        }
    }
```

But $model->relationXYZ is not giving proper results. To make it working i had to call
```$model->load('relationXYZ');```

After that it works. Is it a bug or I am missing anything? How can I make it working without loading relationship again.

**Comment by jasonlewis** [comment]
Dynamic includes are never a pretty thing, especially when it comes to using Eloquent collections.

I'm going to go out on a limb and say you need to rethink this. What I believe is happening is that because Dingo automatically eager loads your includes, and because this is a collection, it's eager loading for all the models in the collection but it's using the attributes of the first model for the dynamic section.

You can disable eager loading on the adapter if you'd like, either globally, or in the controller method.

```php
app('api.transformer')->getAdapter()->disableEagerLoading();
```

**Comment by weiwenhao** [comment]
@gauravjain028 You can try this [weiwenhao/tree-ql](https://github.com/weiwenhao/tree-ql)
