### ISSUE TITLE
Is this project still upheld?

### ISSUE THREAD

**Issue by manarchliu** [dingo/api#1436]
# Is this project still upheld?

**Comment by thilanga** [comment]
Hi @manarchliu Project has been bit behind due to the busy schedule of @jasonlewis. 

my self and Mano Pastas (@from2day) will be helping to get the project up-to-date.

As the first step we will be looking at all the pull requests been made. To start with priority will be supporting for Laravel 5.5 then moving ahead with issues.

Thanks

**Comment by manarchliu** [comment]
Thank you!

**Comment by nstapelbroek** [comment]
With the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) approaching, is there a road map people can follow in case they want to help?

**Comment by thilanga** [comment]
It's actually a good idea. Let's brainstorm around it. I'll create a project for the new release. 

There are lots of things to be done. I really need to do a cleanup first before adding new features. 

Let me have a chat with @from2day and create a list of items over the weekend.

If you guys want to see some features there. Love to hear that too.
