### ISSUE TITLE
Code doubt: Why convert an empty object into an empty array?

### ISSUE THREAD

**Issue by xiaohuilam** [dingo/api#1569]
https://github.com/dingo/api/blob/14225351b2a9b652f6814851539370645c0c1fac/src/Routing/Router.php#L540

Test: 
```php
use Illuminate\Http\JsonResponse;

new JsonResponse([
    'key' => 1,
    'object' => new \stdClass(),
]);
```

after that JsonResponse instanced data pass that line, it becomes
```json
{
    "key": 1,
    "object": []
}
```

but below format is expected
```json
{
    "key": 1,
    "object": {}
}
```

*Original bug-caused Pull Request* https://github.com/dingo/api/pull/1357
*temporary patch* try using`Symfony\Component\HttpFoundation\JsonResponse` instead of `Illuminate/Http/JsonResponse`

**Comment by specialtactics** [comment]
Hi

I am not sure what you are trying to say or how this relates to dingo. When using Dingo, I would recommend you use only it's own response helper, and not Laravel's responses.

But in either case, this issue you describe is not related to dingo, and it's not something dingo developers can solve because it requires changes to Laravel.
