### ISSUE TITLE
How to use simplePaginate in transform

### ISSUE THREAD

**Issue by zhaoJone** [dingo/api#1607]
| Q | A
| ----------------- | ---
| Bug? | no
| New Feature? | yes
| Framework | Lumen
| Framework version | 5.6
| Package version | 2.0.0-alpha2

#### Actual Behaviour

i want to use simplePaginate for paginate, but when use transform ,simplePaginate not implements class `LengthAwarePaginator`

like this:
```
$model = Model::simplePaginate(20);
return $this->response->paginator($model, new ModelTransformer());
```
Error:
```
"Argument 1 passed to League\\Fractal\\Pagination\\IlluminatePaginatorAdapter::__construct() must be an instance of Illuminate\\Contracts\\Pagination\\LengthAwarePaginator, instance of Illuminate\\Pagination\\Paginator given, called in /shared/httpd/datasys/vendor/dingo/api/src/Transformer/Adapter/Fractal.php on line 132"
```

**Comment by specialtactics** [comment]
Hi there @zhaoJone 

As the stack trace and error would imply, the issue here is actually quite outside of dingo-api and rather in the league fractal package. Thus there's nothing we can actually do to resolve this, since the code belongs to another repo.

I highly recommend you re-submit this issue in their repository, and please link it here, and I will take a look at updating Fractal.

Repo: https://github.com/thephpleague/fractal
