### ISSUE TITLE
Call to a member function toArray() on null

### ISSUE THREAD

**Issue by lyongdee** [dingo/api#1658]
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7.19
| Package version   | 2.2.3
| PHP version       | 7.1.19

#### Actual Behaviour

![8A035BF4-D74A-4f8a-B111-7F07681ED4FC](https://user-images.githubusercontent.com/369124/58155115-da929b80-7ca5-11e9-9183-1d72177ff7c4.png)

As shown in the picture, when running :
`$ php artisan api:routes`
That's will return :
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function toArray() on null

But the code above I wrote works fine, how to solve it.

#### Expected Behaviour

show `api:routes`

#### Steps to Reproduce

List all the steps needed to reproduce the issue you're having. Make sure to include code (affected models, configurations),
any screenshots and/or other resources that may help us understand what's going on.

#### Possible Solutions

If you have any ideas on how to solve the issue, add them here, otherwise you can omit this part.

**Comment by sudkumar** [comment]
@lyongdee Can you run `php artisan` successfully ? Or it is also throwing the same error ?

**Comment by lyongdee** [comment]
@sudkumar `php artisan` is ok, and other commands is ok

**Comment by specialtactics** [comment]
The problem is definitely in your code - It's triggered from your controller.

Even though it may work fine through HTTP - this is irrelevant, because you are not considering what affect your code has when the controller is bootstrapped from CONSOLE for the purposes of that command. This may not matter at all, but if you want to run that command, you need to take this into consideration.
