### ISSUE TITLE
How to debug Fractal\TransformerAbstract

### ISSUE THREAD

**Issue by myself379** [dingo/api#1699]
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.2
| Package version   | 1.0.*@dev
| PHP version       | 7.0

#### Actual Behaviour

I need help in debugging dingo that extend Fractal\TransformerAbstract. I unable to use xdebug due to its in production

#### Expected Behaviour

a easy \Log::info() info dump would be nice. Or error indicated which Dingo\Collection crashes.

#### Steps to Reproduce

in transform() method, give it crash like calling object on undefine property. The whole thing just blow up with 500 server error with no good debug method.

I have API_DEBUG=true in .env

#### Possible Solutions

I have no idea how to bubble up the exception to Sentry.io

  As for now I don't have any idea.

**Comment by specialtactics** [comment]
Hi

This is not a bug or issue, you are essentially asking us to put debugging output in the project because you are not familiar with how to debug your code. If you use sentry, it will tell you exactly where and what whatever problem you are having is, whether it's in application or vendor code - so this is not necessary at all.

Also, you are using a very very old version of everything - PHP, Laravel and the vsion of dingo is not supported at all.
