### ISSUE TITLE
CORS and strict mode

### ISSUE THREAD

**Issue by dbonner1987** [dingo/api#336]
When "strict mode" is enabled, the router parses the Accept header on every request, unfortunately the OPTIONS request cannot be altered and as such, does not include a valid header. 

This immediately throws the "InvalidAcceptHeaderException" exception.

Suggest adding a check for the method in the parse method.

**Comment by jasonlewis** [comment]
Why can't the OPTIONS request be altered?

**Comment by dbonner1987** [comment]
Hi,

By design the preflight can't be altered, preventing the client from accessing a resource it shouldn't. The preflight OPTIONS request is constructed by the browser, all "author request header" values are ignored and the type is set added to the value of the Access-Control-Request-Headers (http://www.w3.org/TR/cors/#preflight-request).

So because the Accept value is ignored on preflight, when strict mode is enabled the request throws a 500.

For example, take a simple request like, not taking authentication into account:

> Request URL:http://api.domain.dev/products
> Request Method:GET
> Accept:application/vnd.vendorname.v1+json
> Accept-Encoding:gzip, deflate
> Accept-Language:en-US,en;q=0.8
> Connection:keep-alive
> Content-Length:46
> Content-Type:application/json;charset=UTF-8
> Host:api.domain.dev
> Origin:http://app.domain-2.dev
> Referer:http://app.domain-2.dev/

The preflight the browser will send is:

> Request URL:http://api.domain.dev/products
> Request Method:OPTIONS
> Accept:\*/\*
> Accept-Encoding:gzip, deflate, sdch
> Accept-Language:en-US,en;q=0.8
> Access-Control-Request-Headers:accept
> Access-Control-Request-Method:GET
> Connection:keep-alive
> Host:api.domain.dev
> Origin:http://app.domain-2.dev
> Referer:http://app.domain-2.dev/

Github has a similar example: https://developer.github.com/v3/#cross-origin-resource-sharing

The OPTIONS request is purely to establish what capabilities/permissions are valid for CORS interaction, altering the "parseAcceptHeader" method seems like the simplest fix. The vendor/version isn't required for such a request.

Cheers mate

**Comment by dbonner1987** [comment]
I've just pushed a simpler solution that checks for the OPTIONS request at the start of the dispatch method whilst checking if it is an api request. 

Laravel has built-in support to handle these request automatically, this prevents the package having to run through and build a response of it's own.

Cheers

**Comment by jasonlewis** [comment]
Hm, if that's the case then if you have a route that's only available on `v2` of your API, and you attempt an `OPTIONS` request on it, it'll fail..

**Comment by dbonner1987** [comment]
Route versioning isn't an issue, I've tested requests to various routes and because we are checking for the `OPTIONS` method before any check against the version is made, it works as expected. 

The Accept header with a version string is only sent in the subsequent request when a `204 No Content` response is received by the browser.

With the following Route groups, a request to either v1 `http://api.domain.com/authenticate` or v2 `http://api.domain.com/authenticate-secondary` works accordingly.

```php
Route::api([
    'version'   => 'v1',
    'protected' => false,
    'domain'    => 'api.domain.com'
], function() {

    Route::post('authenticate', ['uses' => 'AuthApiController@authenticate']);

});


Route::api([
    'version'   => 'v2',
    'protected' => false,
    'domain'    => 'api.domain.com'
], function() {

    Route::post('authenticate-secondary', ['uses' => 'AuthApiController@authenticateSecondary']);

});
```

I was initially testing with Angular, though this jQuery works as above.

```javascript
$.ajax({
    url: 'http://api.domain.com/authenticate',
    type: 'POST',
    async: true,
    dataType: "json",
    data: JSON.stringify({
        email: 'email@email.com',
        password: 'password'
    }),
    headers: {'Accept': 'application/vnd.wcscpd.v1+json'},
    crossDomain: true,
    contentType: 'application/json; charset=UTF-8',
    success: function (data) {
        console.log(data);
    }
});

$.ajax({
    url: 'http://api.domain.com/tester',
    type: 'POST',
    async: true,
    dataType: "json",
    data: JSON.stringify({
        email: 'email@email.com',
        password: 'password'
    }),
    headers: {'Accept': 'application/vnd.wcscpd.v2+json'},
    crossDomain: true,
    contentType: 'application/json; charset=UTF-8',
    success: function (data) {
        console.log(data);
    }
});
```

The preflight `OPTIONS` request is sent (Accept header ignored), a `204` is returned by Laravel and the browser will then send the actual request with the defined Accept header in place, `application/vnd.vendorName.v1+json` or `application/vnd.vendorName.v2+json`.

Cheers

**Comment by jasonlewis** [comment]
No, something isn't right there. Looks like routes specified for version 2 are being added to version 1 as well. That shouldn't be happening.

**Comment by jasonlewis** [comment]
I've patched this so it now adds routes correctly. Pull down the latest master changes. I have a feeling the preflights will now fail. I might be able to fix this though so that it will find the correct route for preflights.

**Comment by dbonner1987** [comment]
I've narrowed the issue down to the `domain` option.

When the `domain` option is set (api.domain.com), the version no. appears to be ignored. However when it is removed the the `domain` option throws a 404 as expected.

```php
Route::api([
    'version'   => 'v1',
    'protected' => false,
], function() {

    Route::post('authenticate', ['uses' => 'AuthApiController@authenticate']);

});
```

**Comment by jasonlewis** [comment]
Almost posted at the same time! Check my post just above yours. I've pushed a patch. I'll look into preflights tomorrow though. Need to do a bit of tidying up I think.

**Comment by jasonlewis** [comment]
I've pushed up more changes to master that will hopefully allow all preflights now.

The logic is as follows and I'm going to amend the documentation to better show this...

Basically any request is now first attempted to be matched on the main application routes. My reasoning is that all your API endpoints should fall under either a subdomain or some sort of global prefix, hence they should never really conflict with existing application routes.

If the request is unable to be matched by the application routes the API side of things takes over. Because you can have multiple versions the API will search in reverse order (this, of course, assumes your routes file has version 1 at the top and version 2 underneath that, and so on) and match the first group it comes across. It will first check to see if the request is an OPTIONS request, and if so, attempt to match a route for that request. If it matches then all is well and it returns the 200 OK with the access control headers. Preflight is done.

If it's not an OPTIONS request then it simply continues to check for the route in the group as per normal.

The main things to be aware of here is the ordering of your routes. The recommended way is to list version 1 routes at the top and continue from there. That's how I was imaging people would do it anyway.

**Comment by eduardmartinez** [comment]
Hi @jasonlewis. Thanks for this great package. I have the same problem described above and even if I update the package (it is already updated), the preflight requests don't pass. All because of the Accept header and the strict mode. I have already defined the domain (api.myapp.com) and the app version (v1)  and defined the Accept header from the frontend as you said on wiki but it is still rejected on OPTIONS preflight request. I don't know what else to do. Please, help me.

**Comment by jasonlewis** [comment]
@eduardmartinez, can you try an update now, I've pushed a fix that let's OPTIONS requests validate correctly when facing a strict header.

**Comment by eduardmartinez** [comment]
@jasonlewis Thanks! It works like a charm.

**Comment by ghprod** [comment]
Hi

I've setup some route to work only for `v2`, then the problem is OPTIONS request always ignore Accept version header,

So dingo will try to resolve for `v1` route collection and results 404..

```js
      $.ajax({
        url: 'http://domain.com/some-route/method',
        type: 'GET',
        headers: {
          'Accept': 'application/x.app.v2+json'
        },
        dataType: 'json'
      })
```

any idea how to fix it?
