### ISSUE TITLE
Empty array returned instead of object when there is no link in the pagination

### ISSUE THREAD

**Issue by prapats** [dingo/api#338]
Hi,

When the number of items in a collection is less than the number of item per page of pagination, an empty array is returned. 

## Returned:
```
"meta": {
	"pagination": {
		"total": 5,
		"count": 5,
		"per_page": 15,
		"current_page": 1,
		"total_pages": 1,
		"links": [ ]
	}
}
```

## Expecting:
```
"meta": {
	"pagination": {
		"total": 5,
		"count": 5,
		"per_page": 15,
		"current_page": 1,
		"total_pages": 1,
		"links": { }
	}
}
```
I don't know this is related to #263  or not, but I guess it might not be. As that issue is dealing with an empty collection.

Thank you

**Comment by dbonner1987** [comment]
Hi @prapats,

The returned behaviour is correct. This is the behaviour by default of PHP's `json_encode()` (http://php.net/manual/en/function.json-encode.php).

In order to output the behaviour you're expecting, you will need to create your own `ResponseFormat` class and register it in the config, either replacing the current json one or adding a new one:

```php
'formats' => [

    'json' => 'Dingo\Api\Http\ResponseFormat\MyJsonResponseFormat',
    // OR
    'json-forced' => 'My\Package\Http\MyJsonResponseFormat',

]
```

Copy the contents of `Dingo\Api\Http\ResponseFormat\JsonResponseFormat` and replace the `encode()` method with the following, this will force PHP to return empty arrays as object:

```php
protected function encode($content)
{
    return json_encode($content, JSON_FORCE_OBJECT);
}
```

**Comment by prapats** [comment]
Hi @dbonner1987, 
Thanks for your suggestion; however, for the consistency wise, I think the framework should return empty object as same as when it is returning the normal links object, should't it? The reasons being, in my opinion, is I can use the same code to read the links object (don't have to check whether the links is an object or array. Regarding to solved issue, #263, I could see that the links object should be returned not an array.

Please suggest if I misunderstood something.
Thank you.

**Comment by dbonner1987** [comment]
I get where your coming from, a consistent response is important.

For the time being, using my suggestion above will solve your problem, instead of copying the full contents of the class, just extend `JsonResponseFormat` and add a new `encode()` method.

As a bit of background on the construction of the pagination array. It is built by `League\Fractal\Serializer\ArraySerializer` (line 82) - you'll notice an empty array is created before any links are added, because there are no links, it remains as an non-associative array.

Perhaps a new format could be added to the package - `JsonForcedResponseFormat`. As mentioned above, all that would be required is extending the current one, thus providing the choice to the developer.

```php
<?php

namespace Dingo\Api\Http\ResponseFormat;

use Illuminate\Support\Contracts\ArrayableInterface;

class JsonForcedResponseFormat extends JsonResponseFormat
{
    /**
     * Encode the content to its JSON representation.
     *
     * @param string $content
     *
     * @return string
     */    
    protected function encode($content)
    {
        return json_encode($content, JSON_FORCE_OBJECT);
    }
}
```

Having the option would be my preference over having it forced upon the developer.

Hopefully this will help in the short-term @prapats.

Cheers

**Comment by prapats** [comment]
@dbonner1987 I got your point. Thanks a lot for the information above, it is very useful. I will try to use your solution very soon.

Thanks again,
Cheers

**Comment by jasonlewis** [comment]
What would be the negatives of forcing objects in the default `JsonResponseFormat`?

**Comment by dbonner1987** [comment]
I see no downside in forcing an object by default. My only concern would be that the empty array vs object issues won't be specific to the paginator and any empty array will be returned in the same manner. Any change to the default response may result in issues with client applications that implement logic to handle the empty array and object. 

I wouldn't consider it a breaking change though and providing detail on how to return the old response (an empty array) with a custom `ResponseFormat` would be sufficient?

**Comment by prapats** [comment]
I found that when I was using the `JSON_FORCE_OBJECT`option in the `encode` method, the index of the element will be shown in the response as well. I don't know this would make any consequence afterwards. 

**Without `JSON_FORCE_OBJECT`**
```
{
  "data": [
    {
      "id": 1,
      "name": "Tromp, Turcotte and Zboncak"
    }
  ],
  "meta": {
    "pagination": {
      "total": 5,
      "count": 5,
      "per_page": 15,
      "current_page": 1,
      "total_pages": 1,
      "links": []
    }
  }
}
```

**With `JSON_FORCE_OBJECT`**
```
{
  "data": {
    "0": {
      "id": 1,
      "name": "Tromp, Turcotte and Zboncak"
    }
  },
  "meta": {
    "pagination": {
      "total": 5,
      "count": 5,
      "per_page": 15,
      "current_page": 1,
      "total_pages": 1,
      "links": {}
    }
  }
}
```

**Comment by dbonner1987** [comment]
@prapats see my previous comment, unfortunately, this is the downside to the `JSON_FORCE_OBJECT` flag. Any non-associative will be converted to an object. This shouldn't be a major issue if the client code is only looping through `data` (dependant on the language being used).

If you are only looking to make the `links` object consistent I'd suggest:

* Checking for it's existence in `encode()`;
* Cast it as an object `$content['meta']['pagination']['links'] = (object) $content['meta']['pagination']['links'];` (NB. this is hypothetical, you'll need to test and amend appropriately);
* Then run `json_encode($content)` without the `JSON_FORCE_OBJECT` flag.

**Comment by jasonlewis** [comment]
Yeah if that's what it's going to turn out like then I don't think we'll force it to be an object.
