### ISSUE TITLE
Dispatcher Internal Request Exception Error

### ISSUE THREAD

**Issue by czmole** [dingo/api#345]
I've noticed that when issuing internal request, in case of error it was throwing an InternalHttpException (line 545 on https://github.com/dingo/api/blob/master/src/Dispatcher.php)

My case was 

$updateProfile = API::with([
                            'id'=> Input::get('id'),
                            'firstname'=> Input::get('firstname'),
                            'lastname'=> Input::get('lastname'),
                            'email'=> Input::get('email'),
                            'avatar_url'=> Input::get('avatar_url'),
                          ])->put('api-merchant/users/profile-update');

I've did a change on sending $response = $response->getOriginalContent(); in any case

I don't know if its the best solution but it helped.

Looking forward for a feedback.

Thank you.

**Comment by jasonlewis** [comment]
It only throws the `InternalHttpException` when you're returning an error response from your API route. When you call your API routes internally the API wants to throw exceptions instead of simply returning the response object. This makes it easier to handle errors when you internally call your routes.

The `InternalHttpException` does have a `getResponse` method so you can get the original response object once you've caught the exception.
