### ISSUE TITLE
Catch and Decorate the Request before Dingo Router gets to it

### ISSUE THREAD

**Issue by davidstanley01** [dingo/api#354]
So here's a weird question...

I'm trying to intercept and decorate the request *before* dingo has had a chance to catch and clone it.  Using the PHPLeague OAuth2 package and OAuth2-Server-Laravel bridge for authentication. 

There are 2 methods to use the API.  First is through regular client credentials and standard access using Authorization Header.  Second is through Authenticated UI.  

For the UI access, I want to save the access token to a cookie can only be read by the server.  On a request where there is no Authorization header AND the cookie is present, I'd like to grab the access token, add the Authorization header to the request, and pass it long the way.

I've tried this with a middleware, a Route filter, as well as in the App::before() filter.  Each time, I can grab and decorate the request object, but dingo doesn't respect (or even use, maybe) the newly-decorated request.

I can provide code samples if needed, but just thought I'd ask, first.

Thanks.

**Comment by jasonlewis** [comment]
Sorry for the very late reply David.

Hm, this sounds similar to how I'm working a current project. We have a proxy setup that all API requests are routed through so as we can safely store OAuth tokens without the client having to be responsible for that. The proxy is mainly responsible for reading this cookie and attaching the correct authorization header. Instead of altering the request though the proxy does an internal API call using the dispatcher.

Perhaps give something like that a crack?

**Comment by davidstanley01** [comment]
That makes sense... I'm trying to avoid using a proxy as it adds a layer of complexity.

I don't think I'll be able to avoid that, though.

Thanks for the assistance.
