### ISSUE TITLE
Slow Performance using Model::with('some', 'params')->find($id)

### ISSUE THREAD

**Issue by martinza** [dingo/api#368]
I have an application that utilizes many joins using the "with" function within laravel. The goal of this is to limit the amount of I/Os hitting the database. 

Prior to incorporating Dingo, I was spending about 20ms (including reaching the server and getting a response back) within the controller. Now, I spend about 1500ms waiting for the same info. Maybe this is just a lack of understanding in how dingo works.

**Comment by bweston92** [comment]
You've not posted any code for us to understand how you're doing stuff.

**Comment by potsky** [comment]
Hi,

this is perhaps related but since I have loaded the Dingo Api Service Provider, my requests are 1000ms slower. I don't use Dingo Api yet. I just load the web home page of my website. If I comment Dingo Api Service Provider in `app/config/app.php`, I fall back in 500ms instead of 1500ms.

I have tuned with xhprof and I can see that when loading the Service Provider, I have only 1 call to 'Illuminate\Routing\Controller::__call' and this call last 1000ms. This call is done by `Dingo\Api\Routing\ControllerDispatcher::injectControllerDependencies`.

Without loading the Dingo Api Service Provider, 'Illuminate\Routing\Controller::__call' is never called.

I will try to investigate tomorrow to understand what does Dingo Api with `Illuminate\Routing\Controller::__call` and especially why it last more than 1000ms. I will try to disable some packages to see if there is a incompatibility.

If someone want to investigate, I can open a ngrok proxy to my local machine to xhprof.

I use version 0.8.2 of dingo/api on Laravel 4.2.

**Comment by bweston92** [comment]
With Laravel 4.2 and package at 0.8.2 I can maintain a response time under 100ms without, no ssd/caching either.



—

**Comment by potsky** [comment]
Sure. In my page at 500ms, I have more than 30 mongo requests.

I just have noticed that Dingo API runs perfectly on pages where Mongo DB is not used. I will continue my investigations tomorrow.

**Comment by potsky** [comment]
Ok I have found the way to reproduce the problem. This is perhaps not related to the initial problem encountered by @martinza and this is not related to MongoDB as I previously thought.

If I load a route with a function and by returning a view directly, the page is rendered in 200ms :

```
Route::get( '/' , array( 'as' => 'home' , function() { return View::make( 'frontend.www.home'    ); } ) );
```

But if I load a route with a Controller, the page is rendered in 1100ms :

```
Route::get( '/' , 'HomeController@wwwHome' );
```

with this `HomeController` class :

```
class HomeController extends BaseController
{
    public function wwwHome() {
        return View::make( 'frontend.www.home' );
    }
}
```

**Comment by potsky** [comment]
Here is a diff for the url `/slow` when I activate dingo/api in service providers or not. Don't forget that I don't use dingo api yet.

Route : `Route::get( 'slow' , 'HomeController@slow' );`

Class :

```
class HomeController extends BaseController
{

    public function slow() {
        return 'slow';
    }
    
}
```

Screenshot of the difference between both calls :

![screenshot 2015-03-19 12 44 22](https://cloud.githubusercontent.com/assets/408237/6729722/af7ee1b0-ce35-11e4-964f-f84bbe63d8db.png)

When disabling dingo/api in service providers, `Illuminate\Routing\Controller::__call` is never ran.

**Comment by potsky** [comment]
Ok I have found the problem. This is a VERY VERY VERY common problem : I don't have read the doc :-)

Even if you don't use dingo/api, you MUST change the BaseController as specified here : <https://github.com/dingo/api/wiki/Responses>

If not changed, the run will call the undefined method `setDispatcher` and then the method `Illuminate\Routing\Controller::__call` will throw an exception and exceptions with xdebug are really really really slow to be handled.

**Comment by bweston92** [comment]
Only if your routes are in `Route::api` group they need to extend the Dingo controller.

**Comment by potsky** [comment]
Unfortunately I don't use `Route::api` yet
