### ISSUE TITLE
Return a global authenticated user variable

### ISSUE THREAD

**Issue by MovingGifts** [dingo/api#510]
Instead of using this everywhere $this->auth->user(), is it possible to assign it to a variable like this:

    $authUser = $this->auth->user();

And use it globally? I tried adding it to a __construct method of the BaseController but doesn't work when calling the `$authUser` from any controller that extends it. What would be the correct way to do this?

**Comment by jasonlewis** [comment]
You can just use $this->user() as a shortcut. That's a part of the helpers
trait.

**Comment by MovingGifts** [comment]
Yup that works - thanks! Just out of curiosity, if I were to assign it to a variable, how would I do that (not to assign the same variable in every controller of course) but have global access to it in all controllers, just like we have global access to $this->user(). Any pros/cons in doing that?

Thanks for the lightning fast response btw :)

**Comment by alexcoffee** [comment]
Is it discouraged to create an Alias for it? Like we had the API::user() alias in v0.8?

**Comment by jasonlewis** [comment]
That alias was a facade. I'll most likely be adding facades back at some point in time but I'm not sure if it's all going to be under the `API` facade or if I'm going to have `API\Auth` and so on. Still something I'm thinking about.

@MovingGifts I'm not sure what you mean exactly. If your controllers use the trait you have access to it. Otherwise, you can use `app('Dingo\Api\Auth\Auth')->user()` or `app('api.auth')->user()` to also fetch the authentication user.
