### ISSUE TITLE
Throttling doesn't appear to do anything

### ISSUE THREAD

**Issue by tr33m4n** [dingo/api#575]
Hello there,

I've enabled throttling on my routes, however throttling appears not to affect them. This is my routes.php:
```php
$api->version('v1', ['middleware' => 'api.throttle', 'limit' => 300, 'expires' => 1, 'namespace' => 'App\Http\Controllers'], function ($api) {
	$api->group(['prefix' => 'orders'], function($api) {
		$api->get('/', 'OrdersController@index');
		$api->get('show/{id:[0-9]+}', 'OrdersController@show');
		$api->get('search/{string:[a-zA-z\-]+}', 'OrdersController@search');
		$api->post('/', 'OrdersController@post');
		$api->put('/{id:[0-9]+}', 'OrdersController@update');
		$api->delete('/{id:[0-9]+}', 'OrdersController@delete');
	});
});
```
I've also tried setting the throttle on the group as well with no success. I ran siege on the routes, making 375 requests over 38 seconds and all received status 200.

Any ideas?
Cheers,
Dan

**Comment by jasonlewis** [comment]
How are you testing this, what caching driver are you using and are the rate limiting headers being returned? You should have `X-RateLimit-Limit` and `X-RateLimit-Remaining`.

**Comment by tr33m4n** [comment]
I'm using Redis for caching and yes, those headers are being returned... I guess in that case siege is ignoring the headers? It shouldn't do though. How odd

**Comment by jasonlewis** [comment]
Hm, I just tested with Siege on my end, same limit of 300 and same expiration of 1 minute.

https://dl.dropboxusercontent.com/1/view/2uz45xd8jf7ver6/Apps/Shutter/Selection_005.png

Seems to return 403 fine for me after the 300th request. This is with the Memcached driver. You're hitting a single endpoint correct? The 300 limit is for each route and not as a total for that group.

**Comment by jasonlewis** [comment]
If you run it for a bit, then use `siege -g URL` what do the rate limiting headers show you?

**Comment by tr33m4n** [comment]
Ah, that's where I've misunderstood, I thought if I set a limit on a group then it would set the limit for the whole group rather than each route. I can work with that though, thanks. Do you know of a way of limiting the whole group per chance? Cheers

**Comment by jasonlewis** [comment]
Yeah mate you'll need to create a custom group based throttle. Pretty easy actually.

Throttle just needs to either extend the abstract `Dingo\Api\Http\RateLimit\Throttle\Throttle` or implement the contract `Dingo\Api\Contract\Http\RateLimit\Throttle`.

The only real difference is the abstract will let you pass in an array of options, like this:

```php
$throttle = new YourThrottle(['limit' => 300, 'expires' => 10]);
```

But, the contract has the benefit of being created via the container because you define the options in getters. So, let's use the contract.

```php
class GroupThrottle implements Dingo\Api\Contract\Http\RateLimit\Throttle
{
    public function match(Illuminate\Container\Container $container)
    {
        return true;
    }

    public function getExpires()
    {
        return 1;
    }

    public function getLimit()
    {
        return 300;
    }
}
```

Then just simply list the throttle in your version group (or any other group for that matter).

```php
$api->version('v1', ['prefix' => 'api', 'middleware' => 'api.throttle', 'throttle' => 'GroupThrottle'], function($api) {
    $api->get('/', function () {
        return ['foo' => 'bar'];
    });

    $api->get('users', function () {
        return ['foo' => 'bar'];
    });
});
```

Just a heads up you probably need to run a `composer update` because using a string based and contract inheriting throttle wasn't working. I had to tweak a couple things and fix some tests.

I also need to document this functionality (being able to define a throttle on a route/controller/group).

**Comment by tr33m4n** [comment]
Nice, cheers man, really helped me out :)

**Comment by mohbakh** [comment]
@ @ @ @ @ @ @eduacostam
