### ISSUE TITLE
Do not run middleware if exception is thrown

### ISSUE THREAD

**Issue by Zyles** [dingo/api#612]
Hi, me again...

I have a really simple middleware which runs on every request and adds a key value to the JSON response. But I do not want to run it if there is an exception thrown and dingo shows the error message.

Right now dingo generates the error message, then my middleware runs and adds my custom value after.

Is it possible to tell it somehow not to run middleware if exception is thrown? Or at least run middleware, but detect if exception is thrown so I can use an if statement and ommit the middleware code.

**Comment by jasonlewis** [comment]
Is this in a Laravel or Lumen install?

**Comment by Zyles** [comment]
Lumen.

Perhaps there is a simple variable to check "if exception true" ?

**Comment by jasonlewis** [comment]
I'll take a look when I can. This might be how Lumen does it.

**Comment by jasonlewis** [comment]
This is a very late reply so I'm sorry for that.

I'm curious, but how is the exception being generated? Can you supply some sample code. I'm mulling this over now and perhaps it's because you're returning an error response?

In this case you should use the status code of the response in your middleware to check if it's not a 4xx status code.

```php
$statusCode = $response->getStatusCode();

if ($statusCode >= 200 && $statusCode < 300) {
    // apply custom key to response because we have an OK status code
}
```

Let me know if this needs further looking at.
