### ISSUE TITLE
Middleware api.auth not doing it's job properly.

### ISSUE THREAD

**Issue by zanechua** [dingo/api#739]
I have just utilised this package to create an api for one of my projects but realise that the middleware api.auth is not doing it's job properly.

    Routes:
    $api->get('company/{company}', 'CompanyController@getCompany');

    CompanyController:
    public function getCompany(Company $company)
	{ 
		return response()->json($company);
	}

The above is an example of my routes so I would need to do a get request to http://localhost/api/company/id

The expected response if the company does not exist at the id is a 401 if I did not supply a token. However in this case it's returning a 404 Not Found.

What this does is tells the requester whether there is a record found or not. If i send a request with a record of 1 and there is a record with the ID 1 but i fail to supply the JWT Token, It returns me a 401 which is the correct response.

Why is api.auth not working and returning a 404 instead of a 401 on my routes if the record does not exist at the ID, It shouldn't even let the query be ran without Token and it should instantly return a 401.

Is this intended to work like this or?

**Comment by jlien-calwater** [comment]
@zanechua I believe it is rendering correctly based on the route you have on there.

See: http://laravel.com/docs/5.1/routing#parameters-optional-parameters

```php
// route http://localhost/api/company/id (where ID is required)
// which means http://localhost/api/company/ is an invalid route
$api->get('company/{company}', 'CompanyController@getCompany');

// what you really want is this
$api->get('company/{company?}', 'CompanyController@getCompany');

// make sure to give your variable a default value, e.g., $company = null
```

**Comment by zanechua** [comment]
@jlien-calwater 

You might have mistaken the point of the above issue.

I never said I am calling for http://localhost/api/company/.

I mentioned that I am calling http://localhost/api/company/ID. Notice the ID at the back. I am asking for an ID which has been supplied to the route and in this case it's telling me 404 not found if there is no record but and when I am NOT authenticated (meaning I did not supply a token). On the otherhand, if i didn't supply a token and call for an ID which does exist in the database, it returns a 401 Response.

Hope you understand it's not the same issue that you mentioned. I do use the option parameters in the other routes I have available.

**Comment by jasonlewis** [comment]
What's passed in the URI isn't even considered by the middleware, so it shouldn't be an issue. The middleware will merely attempt to validate the request (authorized or not), if not it'll return a 401.

I'm unable to replicate this. The auth middleware always returns a 401 for me, unless, of course, the URI itself does not exist (route hasn't been created).

**Comment by zanechua** [comment]
@jasonlewis 

Unable to replicate this with what setup? Do you need me to post mine?

**Comment by jasonlewis** [comment]
The middleware is considered for all routes that have a definition, yes.

The middleware itself doesn't care for the URI or anything though.

So you're using route model binding as well then? Can I see your setup then. These are things you need to post so I can try to replicate. In all my testing the route itself is NEVER fired during the authentication and will only be fired if authentication succeeds.

**Comment by zanechua** [comment]
Yeah I am using route model binding. Give me some time, A bit busy at the moment. Sorry about that.

**Comment by jasonlewis** [comment]
I'll re-open and do a bit more fiddling when I can. Got a busy weekend ahead though.

Roger, would love to grab your source and have a play if you can get it up somewhere where I can privately pull it down and have a look. Maybe BitBucket?

**Comment by zanechua** [comment]
As promised. 

I wrote up a similar codebase that has this exact issue.

https://github.com/zanechua/dingotest

Set-up commands:
composer install
php artisan migrate
php artisan db:seed

Api Documentation is in http://dingotest.site/apidoc

**Comment by jasonlewis** [comment]
Cheers.

Won't be able to give this a good look until earlier in the new year.

Thanks for getting it up. I will be looking at it when I can! :+1: :smile:

**Comment by jasonlewis** [comment]
I've finally managed to get around to this, here's what I've discovered.

Route model binding is triggered before middlewares are run on a route. This happens because the model binding occurs when the route is matched. Laravel attempts to replace the bindings in your route (in this case, `{user}`) with the appropriate binding (a valid instance of `App\Model\User`).

If Laravel is unable to resolve a model instance then it throws a `NotFoundHttpException`, hence the 404. Again, this happens before middleware has been fired on the route, so we still haven't been authenticated yet.

I'm unsure of what I could do here to resolve something like this. It's not ideal, but that's how model binding works.

Possible solutions are to not use model binding, accept that this is how the responses will be, or try something like this...

```php
$router->model('user', 'App\Models\User', function ($value) use ($router) {
    $route = app('Dingo\Api\Routing\Router')->createRoute($router->current());

    app('Dingo\Api\Routing\Router')->setCurrentRoute($route);

    if (isset($route->getMiddleware()['api.auth'])) {
        app('Dingo\Api\Auth\Auth')->authenticate($route->getAuthProviders());
    }
    
    throw new NotFoundHttpException;
});
```

When you bind the model to the parameter in the service provider pass in the closure that's executed when the model cannot be found. In it we'll create a new Dingo route instance from the current Laravel route.

Then we need to set the current route on the Dingo router. The reason we need to do this is because of how early model binding is executed none of this has been set yet.

Once we've done that we can check the middlewares on the route and see if the `api.auth` middleware is there. If it is we'll attempt to authenticate the request. If it passes, we'll move down and, because the model does not exist, simply throw the `NotFoundHttpException` like usual.

However, if authentication fails, then we'll get an `UnauthorizedHttpException` as we'd expect.

Hopefully this helps.

**Comment by zanechua** [comment]
@jasonlewis 

Hey! 

I'm just revisiting this issue as I'm now almost finished with the app I'm working on and I came back to take a look at securing the api's and all. I consider this a security flaw. I'm not sure why i didn't google the other time but I did and apparently it's not only me that was facing this issue.

Thanks for providing the solution previously.

Here's the full discussion over at https://github.com/laravel/framework/issues/6118
