### ISSUE TITLE
Authentication & Versioning Flexibility/Configuration

### ISSUE THREAD

**Issue by stevegitau** [dingo/api#79]
a) The library should handle different Authentication mechanisms like OAuth 2.0 and  HMAC authentication. A developer should be able to use which Authentication mechanism to use.

b) API Versioning done in the true REST way should be in the header as is currently implemented. However some people argue about pragmatism as opposed to following dogmas. I therefore propose to also have a way to configure whether the API version should be sent via the header on via the URL.

**Comment by jbrooksuk** [comment]
When writing documentation on different API versions (say with ReadMe.io) it's a darn sight easier if you allow API versioning through the URL.

Perhaps some kind of option to do this?

**Comment by hthabet** [comment]
Hi, I know this conversation started over a year ago but since I recently started using this package. I have a question regarding the Accept Header:
<code>application/STANDARDS_TREE.SUBTYPE.VERSION+json</code>

I set up my app : STANDARDS_TREE=vnd and SUBTYPE=myapp and VERSION=v1

Here's the different cases using the Header and their api response : 
1- <code>application/vnd.myapp.v1+json</code>
Response: 200 OK with the expected output
2- <code>application/vnd.myapp.v2+json</code>
Response 400 (The version given was unknown or has no registered routes.)
*- and then I tried any other combinations like <code>application/x.x.v2+json</code> and I got 200 OK with the expected output which it is weird because there is no v2 in my code and we should expect the error in case 2.

Did I misunderstand something? Probably a bug?

As for API versioning, we can see that many of API providers such as Facebook or Twitter they do have the version in the URL. In my opinion, allowing it through the URL should be considered as an option and could be setup in configuration as it gives us a quick idea about which version of the api we are requesting against.

**Comment by jbroudou** [comment]
I agree that the API versioning should be configurable and that Dingo should support version numbers in the URL. I don't think there is a general consensus as to which way "is best", so ideally Dingo shouldn't force you to use one method over another.

**Comment by jasonlewis** [comment]
You're right, there's no "best way", but most do agree that versioning in the URL is not ideal.

I don't really intend to implement this any time soon. If you can get something working and want to submit a PR, feel free, but I can't guarantee it'll be merged, sorry.

**Comment by joshhornby** [comment]
Anyone used HMAC with this package?

**Comment by jasonz1987** [comment]
SDK or OPEN API PLATFORM need the version on url ,not the version on header FOR user,so anyone can make a branch?
