### ISSUE TITLE
Paginate included items

### ISSUE THREAD

**Issue by lukasoppermann** [dingo/api#791]
If I return a `post` which includes `comments` and I want the comments to be paginated, how could I go about it? The comments are included via a relationship, so I have no query builder, just a straight collection. 

I am using dingo with lumen.

I could not really understand how to achieve this looking at the wiki, the issues, or the fractal page. Thanks for your help.

**Comment by bcarroll22** [comment]
To my knowledge, you can't "paginate" the way you would a resource. You'll have to use Fractal ParamBag to get a limit and an offset on a nested resource. It'd look something like

```
/posts?include=comments:limit(5|1)
```

That's actually straight from the documentation at http://fractal.thephpleague.com/transformers/

**Comment by lukasoppermann** [comment]
Well, but now, the pagination links are not automatically created. Also the user could as for an huge amount of entries. But I would need a way to limit the response by default and provide links to get more entries.

**Comment by bcarroll22** [comment]
I’ve run into problems like this when building APIs also. I think
ultimiately what makes the most sense is to make two API calls in
situations like this. Your first one to /galleries/{ids}, then if you need
the photos, make a call to /galleries/{ids}/photos, because at this route
its easy to pagninate and I think it makes the most sense. And be sure to
include the link to the first page of photos on your galleries response.

**Comment by lukasoppermann** [comment]
Well, yes this works, true.
