### ISSUE TITLE
not getting error messages only status code from $this->response->error()

### ISSUE THREAD

**Issue by saqueib** [dingo/api#813]
Everything was working but now I am `not getting any error msg` from `$this->response->error("error", 422)`.

I have moved my Laravel 5.1 app to Forge with HHVM/3.11.0 and PHP7, ` "dingo/api": "1.0.*@dev"`.

All below returns are giving only status code with not content in response

```php
// returning 401 with empty content
return $this->response->error($user->msg, 401);  

// returning 422 with empty content
return $this->response->error('This email id has been taken.', 422); 
```

Please look into this

**Comment by saqueib** [comment]
issue was something related `cors`

**Comment by saqueib** [comment]
please have a look at barryvdh/laravel-cors#89 its not working.

**Comment by odranoelBR** [comment]
I have the same problem...

**Comment by odranoelBR** [comment]
Buddy i put the Larael cors on global middleware, like said in https://github.com/dingo/api/issues/576.
Now everything works fine. =))

**Comment by jasonlewis** [comment]
This error is because when using those error responses it's actually throwing an `HttpException`, which results in the halting of the route middleware execution, so the CORs headers are never attached.

The global middleware is still applied, hence why it works in that case.

The solution here would be to enable it globally.

I'll try and implement something that makes it easier to apply middleware globally to API only routes, as I think that would be a better solution.

**Comment by jasonlewis** [comment]
Refer to #876 for more.
