### ISSUE TITLE
[L5.1] Transformer does not work with raw queries

### ISSUE THREAD

**Issue by detola1234** [dingo/api#822]
I have an ArticleCommentsController with an index method
```
class ArticleCommentsController extends BaseController
{
    public function index($id)
    {

        $comments = DB::table('comments')
            ->leftJoin('users', 'users.id', '=', 'comments.user_id')
            ->where('comments.article_id', '=', $id)
            ->get();

         return $this->response->item($comments, new CommentTransformer);
    }
}
```
This is the transformer class
```
namespace App\Transformers;

use League\Fractal\TransformerAbstract;

class CommentTransformer extends TransformerAbstract{
    public function transform($comment)
    {
        return $comment; //simplified
    }
}
```
The response is the following error:
```
get_class() expects parameter 1 to be object, array given.
```
Obviously, i need to send an instance of the comment object when calling Fractal\transform but i don't know how to do that since laravel's raw queries only return an array or an instance of the QueryBuilder class.

**Comment by jasonlewis** [comment]
You're using an `item` response but using `get` to fetch multiple comments. Try using `first` in your query to see if you get an object returned then. It doesn't need to be an instance of your `Comment` class it just needs to be identifiable in some way, and arrays can't be used as an identifier.

If you're wanting to fetch multiple records using the query builder then try converting it to a collection instead of an array of query builder instances. Make sense?

**Comment by andrewmclagan** [comment]
Would it not be reasonable to respond with raw arrays?

e.g. Elasticsearch results, Query builder, Mongo ...

Data can originate from more then just a MySQL database.

**Comment by richardbenson** [comment]
@andrewmclagan Did you get anywhere with raw queries?  Am also struggling to return some aggregated mongo results through Dingo
