### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by alexw23** [dingo/api#848]
Just wondering when will you be releasing a beta3 or the likes. The current tag v1.0.0-beta2 is 77 commits behind master.

**Comment by mattvb91** [comment]
:+1:

**Comment by fbingha** [comment]
Yes, please let us know since I am being blocked from upgrading to 5.2 by https://github.com/dingo/api/issues/785

**Comment by kostaspt** [comment]
Same here... I still haven't updated to Laravel 5.2, because I have to lock to a version and beta2 doesn't support it. :(

**Comment by driesvints** [comment]
@jasonlewis do you need any help with releasing a next version? I'll gladly help out any way I can.

**Comment by jasonlewis** [comment]
@driesvints Slowly making my way through the open issues to resolve anything outstanding, so there's always that. Not adding anything feature-wise. Just fixing anything in the issues. Once that's done I'd be happy to tag as 1.0.0.

**Comment by driesvints** [comment]
@jasonlewis awesome! Thanks mate :smile:

**Comment by hskrasek** [comment]
I'm gonna try and help @jasonlewis go through everything so that a 1.0.0 can be tagged. Don't want to promise any dates or anything yet, just barely through page four of the 98 issues open

**Comment by hskrasek** [comment]
I'm currently using this as the best place to give a status update on version 1.0.0. Sadly missed my target deadline I gave myself, due to under estimated the scope of some of the issues logged. I know I was MIA for the past couple of days, but am still working on trying to resolve the final issues to lockdown a v1.0.0.

If you checkout the v1.0.0 milestone and see any issues you think you can PR and resolve, totally not gonna stop you, just saying 😄.

Thanks for the continued patience
