### ISSUE TITLE
collection() expects an array of objects. How to deal with plain array data ?

### ISSUE THREAD

**Issue by morfin** [dingo/api#850]
Hi,

I'm using  Doctrine ORM and I would like to query with ArrayResult for memory issues. The problem is that Dingo collection method expects an array of objects. That forces me to hydrate my ORM collection with full fledged objects, instead of a simple Array result. 

How can I deal with this ?

**Comment by lukasoppermann** [comment]
Maybe I misunderstand you, but couldn't you just use the `response->array()` method?

**Comment by morfin** [comment]
Ok, 

Normally, with a collection of objects, I will use:
'''
return $this->collection($service->getData(), new MyTransformer);
'''

I need something like this:
'''
return $this->arrayCollection($service->getData(), new MyTransformer);
'''

Any idea?

**Comment by jasonlewis** [comment]
The reason both of those methods require an object is so that it can essentially link the object to the transformer, so that when the time comes, it knows that Object A should be transformed by Transformer A.

An array does not have a name associated with it.

So does this array need to be transformed? If no, then just return it directly. If yes, then I'm afraid we're going to have to do some tinkering here.

If it's possible... are you able to just `new Illuminate\Support\Collection($array);`. Because that's all you'd need. Just an object to link to the transformer.
