### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by catalinux** [dingo/api#881]
After the last commits in this project my tests are generating this errror:

`PHP Fatal error:  Call to a member function getAuthenticationProviders() on null in /var/www/www/vendor/dingo/api/src/Http/Middleware/Auth.`

**Comment by jasonlewis** [comment]
Changed a few things up and still tinkering. Can you share one of the tests that's causing the issue?

**Comment by jasonlewis** [comment]
Also is this Lumen or Laravel?

**Comment by catalinux** [comment]
My test:

    public function testExposedMappings()
    {
        $this->get('/api/dictionary', $this->headers)->seeStatusCode(Response::HTTP_OK)->seeJson();

    }

where `$this->headers`

      $user = factory(env('AUTH_MODEL'))->create();
        $jwt = \Tymon\JWTAuth\Facades\JWTAuth::fromUser($user);
        $this->headers = [
            'HTTP_ACCEPT' => 'application/vnd.' . env('API_VENDOR', '') . '.v1+json',
            'HTTP_AUTHORIZATION' => 'Bearer ' . $jwt
        ];

I am using Lumen

**Comment by jasonlewis** [comment]
Yeah, any tests will fail on Lumen at the moment. Trying to work a solution in. Lumen makes things so difficult sometimes. :frowning:

**Comment by jasonlewis** [comment]
Can you pull down the latest changes and let me know if your tests pass now.

Lumen sets the route resolver at a weird and slightly inconvenient point the cycle, and due to the nature of tests it isn't being set. This may or may not be intentional on the Lumen side of things, I'm going to ask Taylor about it.

For now, I've used reflection to set the route resolver on the request whenever it is rebound.

**Comment by catalinux** [comment]
For now everything looks great :)

**Comment by intositeme** [comment]
I know Lumen 5.3 isn't supported yet, but I'm getting the same error.
