### ISSUE TITLE
Dingo\Api\Exception\Handler breaks some Response logic in Laravel

### ISSUE THREAD

**Issue by erroric** [dingo/api#885]
For example, I have session middleware \Illuminate\Session\Middleware\StartSession enabled for route, which controller action throws an UnauthorizedHttpException.
In this case session cookie is missed in response.
This behaviour exists because in `Dingo\Api\Routing\Router#dispatch` an exception handler creates new Response, `$response = $this->exception->handle($exception);`  ignoring previous responses chain and its headers (cookies).
If an Exception occurs in regular Laravel controller action with session middleware enabled, session cookie is not missed.

**Comment by jasonlewis** [comment]
Hm, this is a tough one, mainly because the initial `$response` you see from the `$this->adapter->dispatch()` call doesn't actually exist in the `catch` block, because an exception has been thrown.

All middleware should be terminated correctly so assuming your session data is written prior to the exception being thrown it will be saved to the session once the session middleware is terminated. If you're not seeing this behaviour then make sure you've updated.

I've just tested this and session data is still written correctly.

Also, you shouldn't really be saving state in an API anyway, so sessions shouldn't be an issue. An API is meant to be stateless.

**Comment by erroric** [comment]
>I've just tested this and session data is still written correctly.

Yes, it is, session data written correctly on disk, but session cookie is not sent to the user, because it is missed in response.
This behaviour exists only for first time call to the session handled action, when session cookie is not set yet (for example, first call to the login action, which throws 401).
And here is an inconsistency - session data is written to disk/database, but session cookie is not sent in response.

As I wrote before, when regular Laravel controller throws some exception, session cookie is not missed and correctly sent within error response.

>An API is meant to be stateless
I understand it, but in real world it is not always can be done.

>Hm, this is a tough one, mainly because the initial $response you see from the $this->adapter->dispatch() call doesn't actually exist in the catch block, because an exception has been thrown.

No, it is exists, because an exception thrown after $response variable is set.

Anyway, I have some workaround for this, making a call to some unprotected and not throwable action for get session cookie before do some other API actions.
