### ISSUE TITLE
JSONAPI error format

### ISSUE THREAD

**Issue by rlesniak** [dingo/api#980]
Is there any way to change error format in Dingo API to compatible with JSON API V1? I need this to working with Ember Data 2

**Comment by jasonlewis** [comment]
You can, refer to the wiki: https://github.com/dingo/api/wiki/Configuration#error-format

If this isn't enough then I'd suggest registering a handler for all exceptions and generating your own error responses instead of relying on the package to generate generic ones. Also on the wiki: https://github.com/dingo/api/wiki/Errors-And-Error-Responses#custom-exception-responses

**Comment by oxodesign** [comment]
@rlesniak did you find a solution on this?

**Comment by hskrasek** [comment]
@oxodesign The Wiki links that @jasonlewis linked to are the best solutions to @rlesniak's question. If you checkout out the example [here](https://github.com/dingo/api/wiki/Errors-And-Error-Responses#custom-exception-responses), and swap out the symfony exception for `\Exception`, it'll use that handler for everything.
