### ISSUE TITLE
Controller's constructor runs before the middleware

### ISSUE THREAD

**Issue by HtmHell** [dingo/api#987]
http://stackoverflow.com/questions/36607512/run-middleware-before-controllers-constructor-on-laravel-5-1

**Comment by assembledadam** [comment]
I could be wrong, but I think controller constructor's are supposed to run before the middleware.

**Comment by HtmHell** [comment]
@assembledadam On laravel the middleware runs before the controller's constructor, and the answer I've recieved will work, but the issue still exists - If I want to declare the middleware in my routes, like so:

```
$api->group(['middleware' => 'auth:user'], function() use($api)
{
    $api->get('account', ['as' => 'user.account', 'uses' => 'UserAccountController@index']);
    ...
```
The constructor of `UserAccountController` will run before the middleware, and I will not be able to do something like that:
```
public function __construct()
{
    $this->user = \Auth::user();
    ...
```

**Comment by hskrasek** [comment]
@HtmHell This is something that the framework does on purpose, especially since the framework allows you to define middleware for a controller via its constructor. Because of that, the controller has to be constructed before going through the pipeline.

Coincidentally Taylor actually tweeted about this, with a [note to the upgrade guide for 5.3](https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors) that speaks to this. Basically, it was never intended to be able to access session data, or the authenticated user in the constructor of the controller. One thing he mentions is (the closure middleware) is 5.3 specific, but you may DI the request object into your controllers method(s) and use the `user` method to get the authenticated user. 

Because of this, not much we can fix on the side of dingo, so I'm gonna close this off. Hope my comment was helpful

**Comment by hartantothio** [comment]
@hskrasek -- I also notice this issue. I'm on Laravel 5.2, as soon as I updated my packages, I experience this issue. Below are the updated packages:
```
  - Removing psr/log (1.0.0)
  - Installing psr/log (1.0.1)
    Downloading: 100%

  - Installing webmozart/assert (1.1.0)
    Loading from cache

  - Installing phpdocumentor/reflection-common (1.0)
    Loading from cache

  - Installing phpdocumentor/type-resolver (0.2)
    Loading from cache

  - Removing phpdocumentor/reflection-docblock (2.0.4)
  - Installing phpdocumentor/reflection-docblock (3.1.0)
    Loading from cache

  - Removing dingo/blueprint (v0.1.6)
  - Installing dingo/blueprint (v0.2.0)
    Loading from cache

  - Removing dingo/api (v1.0.0-beta3)
  - Installing dingo/api (dev-master 242411e)
    Loading from cache
```

**Comment by manhhoangnfq** [comment]
It is critical bug, i try to debug in both __constructor of controller and middleware  but __constructor of  controller run before __constructor of middleware.
